[theme]
base = "light"
primaryColor = "#0047AB"             # royal blue
backgroundColor = "#FFFFFF"          # white
secondaryBackgroundColor = "#F5F5F5" # light gray cards/sidebar
textColor = "#000000"
font = "sans serif"


